"
" dotphiles : https://github.com/dotphiles/dotphiles
"
" Setup vim and load required plugins before dotvim
"
" Authors:
"   Ben O'Hara <bohara@gmail.com>
"

" Call dotvim
source ~/.vim/dotvim.vim

if has("user_commands")
  set nocompatible
  filetype off
"   set rtp+=~/.vim/bundle/vundle/
"   call vundle#rc()
"   "let g:vundles=['general', 'git', 'hg', 'programming', 'completion', 'ruby', 'python', 'misc']
"   let g:vundles=['general', 'programming']
"   let g:neocomplcache_enable_at_startup = 1
"   " Load 'vundles'
"   source ~/.vim/vundles.vim
"   " Add extra bundles here...
"   " Bundle 'reponame'
endif

" Customize to your needs...
execute pathogen#infect()
syntax on
if has('gui_running')
    set background=light
    let g:airline_solarized_bg='light'
else
    set background=dark
    let g:airline_solarized_bg='dark'
endif
" let g:solarized_termcolors=256
let g:airline_theme='solarized'
colorscheme solarized
filetype plugin indent on
set number
set scrolloff=3
set ttimeoutlen=10
map <leader>r :so $MYVIMRC
set tabstop=4 
set softtabstop=4
set expandtab
set shiftwidth=4
set smarttab
let g:user_emmet_leader_key = '<Tab>'
let g:user_emmet_settings = {
  \  'javascript.jsx' : {
    \      'extends': 'jsx',
    \  },
  \}

let g:ale_sign_error = '●' " Less aggressive than the default '>>'
let g:ale_sign_warning = '.'
let g:ale_lint_on_enter = 0 " Less distracting when opening a new file
"
" ignore these files when completing names in the explorer
set wildignore=.svn,CVS,*.o,*.a,*.class,*.mo,*.pyc,*.la,*.so,*.obj,*.swp,*.jpg,*.png,*.xpm,*.gif
set autoread

" autocommand to invoke prettify
autocmd BufWritePost *.js AsyncRun -post=checktime ./node_modules/.bin/eslint --fix %
