source /usr/local/share/zsh-antigen/antigen.zsh

antigen use oh-my-zsh
antigen bundle git
antigen bundle common-aliases
# antigen bundle tmuxinator
antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle zsh-users/zsh-history-substring-search ./zsh-history-substring-search.zsh

antigen theme agnoster
antigen apply

# Setup zsh-autosuggestions
source $HOME/.zsh-autosuggestions/autosuggestions.zsh

# Enable autosuggestions automatically
# zle-line-init() {
#       zle autosuggest-start
# }
# zle -N zle-line-init

### ALIASES ###
alias st='git status'
alias gg+='git log --oneline --abbrev-commit --all --graph --decorate --color'
alias gg='gg+ | head -n `expr $LINES / 2`'
alias gs='git status -bs'
alias bx='bundle exec'

